language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t mohabashrafdocker/demo-react-pipeline -f Dockerfile.dev .

script:
  - docker run stephengrider/docker-react npm run test -- --coverage
